# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=150)),
                ('medication', models.CharField(max_length=30)),
                ('initial_visit', models.DateField()),
                ('followup_appt', models.DateField()),
                ('reminder_freq', models.PositiveIntegerField()),
            ],
        ),
    ]
